self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open("app").then((cache) => {
      return cache.addAll([
        "fontawesome/css/all.css",
        "fontawesome/css/app-wa-9a26f71a0382097754e89a94b43cf564.css",
        "fontawesome/css/duotone-light.css",
        "fontawesome/css/duotone-regular.css",
        "fontawesome/css/sharp-duotone-light.css",
        "fontawesome/css/sharp-duotone-regular.css",
        "fontawesome/css/sharp-duotone-solid.css",
        "fontawesome/css/sharp-light.css",
        "fontawesome/css/sharp-regular.css",
        "fontawesome/css/sharp-solid.css",
        "fontawesome/fonts/fa-brands-400.ttf",
        "fontawesome/fonts/fa-brands-400.woff2",
        "fontawesome/fonts/fa-duotone-900.ttf",
        "fontawesome/fonts/fa-duotone-900.woff2",
        "fontawesome/fonts/fa-duotone-light-300.ttf",
        "fontawesome/fonts/fa-duotone-light-300.woff2",
        "fontawesome/fonts/fa-duotone-regular-400.ttf",
        "fontawesome/fonts/fa-duotone-regular-400.woff2",
        "fontawesome/fonts/fa-light-300.ttf",
        "fontawesome/fonts/fa-light-300.woff2",
        "fontawesome/fonts/fa-regular-400.ttf",
        "fontawesome/fonts/fa-regular-400.woff2",
        "fontawesome/fonts/fa-sharp-duotone-light-300.ttf",
        "fontawesome/fonts/fa-sharp-duotone-light-300.woff2",
        "fontawesome/fonts/fa-sharp-duotone-regular-400.ttf",
        "fontawesome/fonts/fa-sharp-duotone-regular-400.woff2",
        "fontawesome/fonts/fa-sharp-duotone-solid-900.ttf",
        "fontawesome/fonts/fa-sharp-duotone-solid-900.woff2",
        "fontawesome/fonts/fa-sharp-light-300.ttf",
        "fontawesome/fonts/fa-sharp-light-300.woff2",
        "fontawesome/fonts/fa-sharp-regular-400.ttf",
        "fontawesome/fonts/fa-sharp-regular-400.woff2",
        "fontawesome/fonts/fa-sharp-solid-900.ttf",
        "fontawesome/fonts/fa-sharp-solid-900.woff2",
        "fontawesome/fonts/fa-solid-900.ttf",
        "fontawesome/fonts/fa-solid-900.woff2",
        "fontawesome/fonts/fa-v4compatibility.ttf",
        "fontawesome/fonts/fa-v4compatibility.woff2",
        "logo.gif",
        "manik.jpg",
        "vpdone.gif",
        "screenshot2.png",
        "lock2.gif",
        "screenshot.png",
        "suc3.gif",
        "suc4.gif",
        "logo_text.png",
        "lock.gif",
        "index2.gif",
        "fall.gif",
        "gift.gif",
        "suc2.gif",
        "suc.gif",
        "lsuc.gif",
        "msuc.gif",
        "edt.gif",
        "udc.gif",
        "done.gif",
        "mail.gif",
        "index.gif",
      ]);
    }),
  );
});

self.addEventListener("fetch", (event) => {
  event.respondWith(
    caches.match(event.request).then((response) => {
      return response || fetch(event.request);
    }),
  );
});
